version: '3.8'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: graphql-demo
    volumes:
      - source: db-data
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: